Enforce amd64 on osx
labellib has compile issues on
osx arm64.

diff --git a/.github/workflows/conda-release.yml b/.github/workflows/conda-release.yml
--- a/.github/workflows/conda-release.yml
+++ b/.github/workflows/conda-release.yml
@@ -49,14 +49,28 @@ jobs:
         with:
           shell: bash -el {0}
           run: |
-            if [[ $RUNNER_OS == "macOS" ]]; then
+            # Check if RUNNER_OS is macOS and set CONDA_SUBDIR accordingly
+            if [[ "$RUNNER_OS" == "macOS" ]]; then
               echo "Running on macOS, exporting CONDA_SUBDIR=osx-amd64"
               export CONDA_SUBDIR=osx-amd64
             fi
+      
+            # Create and activate the build environment
             echo "Creating build environment..."
             conda create -y -n build-env python=${{ matrix.python-version }}
-            source activate build-env
+            conda activate build-env
+      
+            # Install necessary build tools
             conda install -y mamba conda-build boa anaconda-client
+      
+            # Change to the conda-recipe directory and build the package
             cd conda-recipe
             conda mambabuild . --output-folder conda-bld
-            anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u tpeulen --force conda-bld/**/*.tar.bz2
+      
+            # Upload the built package to Anaconda Cloud
+            if command -v anaconda &> /dev/null; then
+              anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u tpeulen --force conda-bld/**/*.tar.bz2
+            else
+              echo "anaconda-client not found, skipping upload."
+              exit 1
+            fi
